#!/bin/bash

script=check-pathnames.lisp

type -p abcl  >/dev/null && (echo abcl  ; abcl  --noinform --batch   --noinit                    --load  $script > check-pathnames-abcl.rst       2>check-pathnames-abcl.err)
type -p alisp >/dev/null && (echo alisp ; alisp  -q         -batch                                -L     $script > check-pathnames-alisp.rst      2>check-pathnames-alisp.err)
type -p ccl   >/dev/null && (echo ccl   ; ccl              --batch   --no-init                   --load  $script > check-pathnames-ccl.rst        2>check-pathnames-ccl.err)
type -p clisp >/dev/null && (echo clisp ; clisp  -q -ansi             -norc                              $script > check-pathnames-clisp.rst      2>check-pathnames-clisp.err)
type -p lisp  >/dev/null && (echo cmucl ; lisp                        -noinit                     -load  $script > check-pathnames-cmucl-20b.rst  2>check-pathnames-cmucl-20b.err)
type -p ecl   >/dev/null && (echo ecl   ; ecl                         -norc                       -load  $script > check-pathnames-ecl.rst        2>check-pathnames-ecl.err)
type -p gcl   >/dev/null && (echo gcl   ; gcl               -batch                                -load  $script > check-pathnames-gcl.rst        2>check-pathnames-gcl.err)
type -p sbcl  >/dev/null && (echo sbcl  ; sbcl  --noinform --noprint --no-userinit  --no-sysinit --load  $script > check-pathnames-sbcl.rst       2>check-pathnames-sbcl.err)

type -p rst2pdf >/dev/null && (for f in *.rst ; do echo rst2pdpf "$f" ; rst2pdf "$f" > "${f/.rst/.pdf}" ; done)


